# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.25
# 

Name:       nemo-qml-plugin-email

# >> macros
# << macros

Summary:    Email plugin for Nemo Mobile
Version:    0.0.0
Release:    1
Group:      System/Libraries
License:    BSD
URL:        https://github.com/nemomobile/nemo-qml-plugin-email
Source0:    %{name}-%{version}.tar.bz2
Source100:  nemo-qml-plugin-email.yaml
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(QtCore) >= 4.7.0
BuildRequires:  pkgconfig(QtDeclarative)
BuildRequires:  pkgconfig(qmfclient)
BuildRequires:  pkgconfig(qmfmessageserver)
Provides:   nemo-qml-plugins-email > 0.3.10
Obsoletes:   nemo-qml-plugins-email <= 0.3.10

%description
%{summary}.

%package devel
Summary:    Nemo email plugin support for C++ applications
Group:      System/Libraries
Requires:   %{name} = %{version}-%{release}

%description devel
%{summary}.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake 

make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake_install

# >> install post
# << install post


%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig

%files
%defattr(-,root,root,-)
%{_libdir}/libnemoemail.so.*
%{_libdir}/qt4/imports/org/nemomobile/email/libnemoemail.so
%{_libdir}/qt4/imports/org/nemomobile/email/qmldir
# >> files
# << files

%files devel
%defattr(-,root,root,-)
%{_libdir}/libnemoemail.so
%{_libdir}/libnemoemail.prl
%{_includedir}/nemoemail/*.h
%{_libdir}/pkgconfig/nemoemail.pc
# >> files devel
# << files devel
